config/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls' , namespace='home')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('' , views.home, name='home'),
    path('products/' , views.all_products, name='products'),
    path('details/<int:id>/' , views.product_details, name='details'),
    path('category/<slug>/<int:id>/' , views.all_products, name='category'),
    path('like/<int:id>/' , views.product_like, name='product_like'),
    path('unlike/<int:id>/' , views.product_unlike, name='product_unlike'),
]

home/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Category(models.Model):
    sub_category = models.ForeignKey('self', related_name='sub', on_delete=models.CASCADE ,null=True , blank=True)
    sub_cat = models.BooleanField(default=False)
    name = models.CharField(max_length=50)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    slug = models.SlugField(allow_unicode=True, unique=True , blank=True , null=True )
    image = models.ImageField(upload_to='Category' , null=True , blank=True)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('home:category' , args=[self.slug , self.id])
class Product(models.Model):
    VARIANT =(
        ('None' , 'none'),
        ('Size' , 'size'),
        ('Color' , 'color'),
    )
    category = models.ManyToManyField(Category, blank=True)
    name = models.CharField(max_length=150)
    amount = models.PositiveSmallIntegerField()
    unit_price = models.IntegerField()
    discount = models.PositiveSmallIntegerField(null=True , blank=True)
    total_price = models.PositiveIntegerField()
    information = models.TextField(null=True , blank=True)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(null=True , choices=VARIANT , blank=True , max_length=20)
    tags = TaggableManager(blank=True)
    image = models.ImageField(upload_to='Product')
    like = models.ManyToManyField(User, blank=True , related_name='product_like')
    unlike = models.ManyToManyField(User, blank=True , related_name='product_unlike')
    total_like = models.PositiveSmallIntegerField(default=0)
    total_unlike = models.PositiveSmallIntegerField(default=0)

    def total_like(self):
        return self.like.count()

    def total_unlike(self):
        return self.unlike.count()

    def __str__(self):
        return self.name

    @property
    def total_price(self):
        if not self.discount:
            return self.unit_price
        elif self.discount:
            total = (self.discount *self.unit_price) / 100
            return  int(self.unit_price - total)
        return self.total_price


class Size(models.Model):
    name = models.CharField(max_length=150)
    def __str__(self):
        return self.name

class Color(models.Model):
    name = models.CharField(max_length=150)
    def __str__(self):
        return self.name

class Variants(models.Model):
    name = models.CharField(max_length=150)
    product_variant = models.ForeignKey(Product, on_delete=models.CASCADE)
    size_variant = models.ForeignKey(Size, on_delete=models.CASCADE , null=True , blank=True)
    color_variant = models.ForeignKey(Color, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.PositiveSmallIntegerField()
    unit_price = models.IntegerField()
    discount = models.PositiveSmallIntegerField(null=True , blank=True)
    total_price = models.PositiveIntegerField()
    def __str__(self):
        return self.name


class Comment(models.Model):
        post = models.ForeignKey(Product, on_delete=models.CASCADE)
        user = models.ForeignKey(User, on_delete=models.CASCADE)
        content = models.TextField(max_length=160)
        timestamp = models.DateTimeField(auto_now_add=True)
        def __str__(self):
            return self.content

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaulttags import comment
from unicodedata import category
from django.contrib.auth.decorators import login_required

from accounts.forms import CommentForm
from .models import *


# Create your views here.
def home(request):
    category = Category.objects.filter(sub_cat=False)
    return render(request , 'home/home.html' , {'category':category})

def all_products(request , slug = None , id=None ):
    products = Product.objects.all()
    category = Category.objects.filter(sub_cat=False)
    if slug and id :
        data = Category.objects.get(slug=slug , id=id)
        products = products.filter(category=data)
    return render(request , 'home/products.html' , {'products':products , 'category':category})

def product_details(request, id):
    product = Product.objects.get(id=id)
    similar = product.tags.similar_objects()[:5]
    is_like = False
    if product.like.filter(id=request.user.id).exists():
        is_like = True

    is_unlike = False
    if product.unlike.filter(id=request.user.id).exists():
        is_unlike = True

    if product.status != 'None' :
        if product.status == 'POST' :
            variant = Variants.objects.filter(product_variant_id=id)
            var_id = request.POST.get('select')
            variants = Variants.objects.get(id=var_id)
        else:
            variant = Variants.objects.filter(product_variant_id =id)
            variants = Variants.objects.get(id=variant[0].id)
        return render(request , 'home/details.html' , {'product':product , 'variants':variants , 'variant':variant , 'similar':similar , 'is_like':is_like , 'is_unlike':is_unlike})
    else:
        return render(request, 'home/details.html', {'product': product , 'similar':similar , 'is_like':is_like , 'is_unlike':is_unlike })

@login_required(login_url='accounts:login')
def product_like(request, id):
    url = request.META['HTTP_REFERER']
    product = Product.objects.get(id=id)
    if product.like.filter(id=id).exists():
        product.like.remove(request.user)
    else:
        product.like.add(request.user)
    return redirect(url)


@login_required(login_url='accounts:login')
def product_unlike(request, id):
    url = request.META['HTTP_REFERER']
    product = Product.objects.get(id=id)
    if product.unlike.filter(id=id).exists():
        product.unlike.remove(request.user)
    else:
        product.unlike.add(request.user)
    return redirect(url)

home/templates/home/details.html
{% extends '_base.html' %}
{% block body %}
	<h1>{{ product.name }}</h1>
    <img src="{{ product.image.url }}" width="200" alt="{{ product.name }}">
    <p> تعداد مجودی : {{ product.amount }}</p>
    <p> {{ product.information }}</p>
    <hr>
    {% if product.status %}
        <form action="" method="post">
        {% csrf_token %}
        {% for data in variant %}
            <input type="radio" value="{{ data.id }} {% if variants.id == data.id %} checked {% endif %}" name="select" onchange="this.form.submit()">
            <a href="" style="text-decoration: none">{{ data.color.variant }}</a>
        {% endfor %}
        </form>
    {% endif %}
    <hr>
    <p>محصولات مشابه</p>
    {% for tag in similar  %}
    	<a href="{% url 'home:details' tag.id %}">
            <img src="{{ tag.image.url }}" width="200" alt="{{ tag.name }}">
        </a>
    {% endfor %}
    <hr>
    <p>like : {{ product.total_like }}</p>
    <p>unlike : {{ product.total_unlike }}</p>
    {% if request.user.is_authenticated %}
    	{% if is_like %}
            <a href="{% url 'home:product_like' product.id %}">
                <i class="bi bi-hand-thumbs-up fs-2" style="color: skyblue"></i>
            </a>
        {% else %}
            <a href="{% url 'home:product_like' product.id %}" class="btn {% if is_unlike %} disabled {% endif %} ">
                <i class="bi bi-hand-thumbs-up-fill fs-2" style="color: skyblue"></i>
            </a>
        {% endif %}
        {% if is_unlike %}
            <a href="{% url 'home:product_unlike' product.id %}">
                <i class="bi bi-hand-thumbs-down-fill fs-2" style="color: skyblue"></i>
            </a>
        {% else %}
            <a href="{% url 'home:product_unlike' product.id %}" class="btn {% if is_like %} disabled {% endif %} ">
                <i class="bi bi-hand-thumbs-down fs-2" style="color: skyblue"></i>
            </a>
        {% endif %}
    {% endif %}
{% endblock %}

home/templates/home/home.html
{% extends '_base.html' %}
{% block title %}
	صفحه اصلی
{% endblock %}
{% block body %}

    {% for cat in category %}
    	<a href="{{ cat.get_absolute_url }}">
            <h1>{{ cat.name }}</h1>
            <img src="{{ cat.image.url }}" width="200" alt="{{ cat.name }}">
        </a>
    {% endfor %}

{% endblock %}

home/templates/home/products.html
{% extends '_base.html' %}
{% block body %}
    {% for data in category %}
    	<a href="{{ data.get_absolute_url }}" >{{ data.name }}</a>
        <div class="btn-group">
        <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"></button>
        <ul class="dropdown-menu">
            {% for info in data.sub.all %}
                <li><a class="dropdown-item" href="{{ info.get_absolute_url }}">{{ info.name }}</a> </li>
            {% endfor %}
        </ul>
        </div>
    {% endfor %}





	{% for product in products %}
		<h1> {{ product.name }}</h1>
        <img src="{{ product.image.url }}" width="200" alt="{{ product.name }}" title="{{ product.name }}">
        {% if product.discount %}
            <h4 style="text-decoration: line-through">{{ product.unit_price }}</h4>
            <h3>{{ product.total_price }}</h3>
            {% else %}
        	    <h3>{{ product.total_price }}</h3>
        {% endif %}
        <a href="{% url 'home:details' product.id%}" class="btn btn-primary">Details</a>
        <p>==============================================================================</p>
	{% endfor %}

{% endblock %}