accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.user_register, name='user_register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.user_profile, name='profile'),
    path('update/', views.user_update, name='update'),
    path('change/' , views.change_password, name='change'),
]
    

config/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('home.urls' , namespace='home')),
    path('accounts/', include('accounts.urls' , namespace='accounts')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('' , views.home, name='home'),
    path('products/' , views.all_products, name='products'),
    path('details/<int:id>/' , views.product_details, name='details'),
    path('category/<slug>/<int:id>/' , views.all_products, name='category'),
    path('like/<int:id>/' , views.product_like, name='product_like'),
    path('unlike/<int:id>/' , views.product_unlike, name='product_unlike'),
]

templates/_base.html
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% include 'navbar.html' %}
    <div class="container">
    {% include 'messages.html'%}
         {% block body %}
         {% endblock %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/messages.html
{% if messages %}
    {% for msg in messages %}
        <h3 {% if msg.tags %} class="alert alert-{{ msg.tags }}"{% endif %}>{{ msg }}</h3>
    {% endfor %}
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">صفحه اصلی</a>
        </li>
              <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:products' %}">محصولات</a>
        </li>
      {% if user.is_authenticated %}
          <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">خروج</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:profile' %}">پروفایل</a>
        </li>
          {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:user_register' %}">ثبت نام</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">ورود</a>
        </li>
      {% endif %}
      </ul>
    </div>
  </div>
</nav>